name: xxxtest6
on: 
  workflow_dispatch:
  
jobs:
  testjob1:
    runs-on: ubuntu-latest
    steps:

      - name: step1
        id:   step1
        run: |
          a=$(echo "0.9999" | awk '{print substr($0, 1, index($0,".")+3)}')
          b=$(echo "0.9" | awk '{print substr($0, 1, index($0,".")+3)}')
          c=$(echo "1" | awk '{print substr($0, 1, index($0,".")+3)}')
          
          echo "<$a>"
          echo "<$b>"
          echo "<$c>"
          echo "aaa"

  