name: xxxtest1
on: 
  push:
    branches:
      - '**'
      - '!master'
      
  workflow_dispatch:
  
jobs:
  testjob1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "佐貫あああ"
      
   