name: xxxtest1
on: 
  push:
    branches:
      - '**'
      - '!master'
      
  workflow_dispatch:
  
jobs:
  testjob1:
    runs-on: ubuntu-latest
    steps:
      - 
        run: |
          echo "佐貫あああ"
          xx="ww"
          case $xx in
            "1"    ) a="aaaa" ;;
            "22"   ) a="bbbb" ;;
            "3333" ) a="cccc" ;;
            *      ) a="xxxx" ;;
          esac
          echo $a
      - 
        run: |
          XX='{"tags": ["sha-7c5a01b5f6b7"]}'
          echo $XX | jq '.tags[] | select(test(":sha-[0-9a-fA-F]{7}$"))'
      
   