name: xxxtest6
on: 
  workflow_dispatch:
  
jobs:
  testjob1:
    runs-on: ubuntu-latest
    steps:

      - name: step1
        run: |
          echo "1"
          exit 1

      - name: step2
        run: |
          echo "2"

      - name: step3
        continue-on-error: true
        run: |
          echo "3"

      - name: step4
        run: |
          echo "4"

      - name: step5
        if: always()
        run: |
          echo "5"

      - name: step6
        run: |
          echo "6"

      - name: step7
        continue-on-error: true
        run: |
          echo "7"

      - name: step8
        run: |
          echo "8"

  