name: xxxtest4

on:
  workflow_dispatch:

env:
  SNK: 'sanuki takaya'

jobs:

  myjob1:
    runs-on: ubuntu-latest
    env:
      ABC: 'aaaa11112222'
    steps:
      - run: |
          echo "SNK $SNK"
          echo "ABC $ABC"
          echo "SNK=cccc vvvv" >> $GITHUB_ENV

      - run: |
          echo "SNK $SNK"
          echo "ABC $ABC"

  myjob2:
    needs: myjob1
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "SNK $SNK"
          echo "ABC $ABC"

