name: xxxtest6
on: 
  workflow_dispatch:
  
jobs:
  testjob1:
    runs-on: ubuntu-latest
    steps:
      - 
        run: |
          echo "1"
      - 
        run: |
          echo "2"
          exit 1
        continue-on-error: true
        id: step1
      - 
        run: |
          echo "3"

        run: |
          echo "4"
          exit 1
        continue-on-error: true
        id: step2

      
      - 
        env:
          S1: ${{ steps.step1.outcome }}
          S1: ${{ steps.step2.outcome }}
        run: |
          echo "S1=$S1"
          echo "S2=$S2"
          
   