name: xxxtest3_A

on:
  workflow_dispatch:

jobs:

  myjob:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "HELLO MAIN"
          echo "佐貫テストあああ" >> $GITHUB_STEP_SUMMARY

  call-workflow:
    needs: [myjob]
    uses: ./.github/workflows/xxxtest3_B.yml
    runs: echo "uuuuuuuuuuu"
