name: xxxtest4

on:
  workflow_dispatch:

env:
  SNK: 'sanuki takaya'

jobs:

  myjob:
    runs-on: ubuntu-latest
    env:
      ABC: 'aaaa11112222'
    steps:
      - run: |
          echo "SNK $SNK"
          echo "SNK ${{env.SNK}}"
          echo "ABC $ABC"
          echo "ABC ${{env.ABC}}"

