name: xxxtest6
on: 
  push:
  
  workflow_dispatch:
  
jobs:
  testjob1:
    runs-on: ubuntu-latest
    steps:

      - name: step1
        id:   step1
        run: |
          echo "0.9999" | awk '{printf "%.1f\n", $1 * 100}'

  