name: xxxtest5
on: 
  workflow_dispatch:
  
jobs:
  testjob1:
    runs-on: ubuntu-latest
    steps:
      - 
        run: |
          echo "111"
      - 
        run: |
          echo "123"
      - 
        run: |
          echo "123"
      
   