name: xxxtest6
on: 
  push:
  
  workflow_dispatch:
  
jobs:
  testjob1:
    runs-on: ubuntu-latest
    steps:

      - name: step1
        id:   step1
        run: |
          echo "1"
          exit 1

      - name: step2
        id:   step2
        run: |
          echo "2"
          echo steps.step1.conclusion

      - name: step3
        id:   step3
        run: |
          echo "3"
          echo steps.step2.conclusion
          

      - name: step4
        id:   step4
        run: |
          echo "4"
          echo steps.step3.conclusion


      - name: step5
        id:   step5
        if: always()
        run: |
          echo "5"
          echo steps.step4.conclusion


      - name: step6
        id:   step6
        run: |
          echo "6"
          echo steps.step5.conclusion

      - name: step7
        id:   step7
        run: |
          echo "7"
          echo steps.step6.conclusion


      - name: step8
        id:   step8
        run: |
          echo "8"
          echo steps.step7.conclusion


  