name: xxxtest7
on: 
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  
  workflow_dispatch:
  
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:

      - 
        run: |
          echo "aaaaaa!!!!!!!!!"
          echo "ref=${{ github.ref }}"
          echo "ref_name=${{ github.ref_name }}"

  